// Generated by gencpp from file ball_chaser/CommandVel.msg
// DO NOT EDIT!


#ifndef BALL_CHASER_MESSAGE_COMMANDVEL_H
#define BALL_CHASER_MESSAGE_COMMANDVEL_H

#include <ros/service_traits.h>


#include <ball_chaser/CommandVelRequest.h>
#include <ball_chaser/CommandVelResponse.h>


namespace ball_chaser
{

struct CommandVel
{

typedef CommandVelRequest Request;
typedef CommandVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandVel
} // namespace ball_chaser


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ball_chaser::CommandVel > {
  static const char* value()
  {
    return "c8652349d2a34a90a09475339e2a93d9";
  }

  static const char* value(const ::ball_chaser::CommandVel&) { return value(); }
};

template<>
struct DataType< ::ball_chaser::CommandVel > {
  static const char* value()
  {
    return "ball_chaser/CommandVel";
  }

  static const char* value(const ::ball_chaser::CommandVel&) { return value(); }
};


// service_traits::MD5Sum< ::ball_chaser::CommandVelRequest> should match 
// service_traits::MD5Sum< ::ball_chaser::CommandVel > 
template<>
struct MD5Sum< ::ball_chaser::CommandVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ball_chaser::CommandVel >::value();
  }
  static const char* value(const ::ball_chaser::CommandVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ball_chaser::CommandVelRequest> should match 
// service_traits::DataType< ::ball_chaser::CommandVel > 
template<>
struct DataType< ::ball_chaser::CommandVelRequest>
{
  static const char* value()
  {
    return DataType< ::ball_chaser::CommandVel >::value();
  }
  static const char* value(const ::ball_chaser::CommandVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ball_chaser::CommandVelResponse> should match 
// service_traits::MD5Sum< ::ball_chaser::CommandVel > 
template<>
struct MD5Sum< ::ball_chaser::CommandVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ball_chaser::CommandVel >::value();
  }
  static const char* value(const ::ball_chaser::CommandVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ball_chaser::CommandVelResponse> should match 
// service_traits::DataType< ::ball_chaser::CommandVel > 
template<>
struct DataType< ::ball_chaser::CommandVelResponse>
{
  static const char* value()
  {
    return DataType< ::ball_chaser::CommandVel >::value();
  }
  static const char* value(const ::ball_chaser::CommandVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BALL_CHASER_MESSAGE_COMMANDVEL_H
